on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Print Ruby and Bundler version
      run: |
        ruby -v
        bundler -v

    - name: build
      run: script/bootstrap

    - name: test
      run: script/cibuild

