on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1.165.1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      # 아래 부분이 제거됨
      #- name: Build
      #  run: |
      #    chmod +x script/bootstrap
      #    script/bootstrap
      - name: Test
        run: |
          chmod +x script/cibuild
          script/cibuild


